# Generated by Django 4.0.6 on 2022-08-05 19:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cash',
            field=models.IntegerField(default=10000, validators=[django.core.validators.MaxValueValidator(1000000000), django.core.validators.MinValueValidator(50)]),
        ),
    ]
