# Generated by Django 4.0.6 on 2022-08-09 14:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_cash_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cash',
            field=models.FloatField(default=10000, validators=[django.core.validators.MaxValueValidator(1000000000), django.core.validators.MinValueValidator(50)]),
        ),
    ]
